export const abbreviations: Array<[string, string]> = [
  ["AAA", "WCAG 2.2 conformance level Triple-A"],
  ["API", "Application Programming Interface"],
  ["CaaS", "Container-as-a-Service"],
  ["CI", "Confidence Interval"],
  ["CO₂", "Carbon Dioxide"],
  ["CPU", "Central Processing Unit"],
  ["CSP", "Content Security Policy"],
  ["DPDP", "Digital Personal Data Protection (Act, 2023)"],
  ["EWMA", "Exponentially Weighted Moving Average"],
  ["FaaS", "Function-as-a-Service"],
  ["GCP", "Google Cloud Platform"],
  ["GCS", "Google Cloud Storage"],
  ["GPU", "Graphics Processing Unit"],
  ["gCO₂/kWh", "grams of Carbon Dioxide per Kilowatt-Hour (grid carbon intensity)"],
  ["HSTS", "HTTP Strict Transport Security"],
  ["HTTP", "Hypertext Transfer Protocol"],
  ["HW", "Holt-Winters seasonal forecasting model"],
  ["IAM", "Identity and Access Management"],
  ["INR", "Indian Rupee"],
  ["JSON", "JavaScript Object Notation"],
  ["JWT", "JSON Web Token"],
  ["MLP", "Minimum Lovable Product"],
  ["p50/p95/p99", "50th / 95th / 99th percentile latency"],
  ["PB", "PocketBase"],
  ["PQC", "Post-Quantum Cryptography"],
  ["QPS", "Queries Per Second"],
  ["REST", "Representational State Transfer"],
  ["RR", "Round-Robin"],
  ["RTL", "Right-to-Left text direction"],
  ["SLA", "Service Level Agreement"],
  ["SLO", "Service Level Objective"],
  ["SPA", "Single-Page Application"],
  ["SQLite", "Embedded SQL Database Engine"],
  ["TLS", "Transport Layer Security"],
  ["UI", "User Interface"],
  ["VPC", "Virtual Private Cloud"],
  ["WCAG", "Web Content Accessibility Guidelines"],
  ["YoY", "Year-over-Year"],
];
